apiVersion: apps/v1
kind: Deployment
metadata:
  name: premerge-advisor
  namespace: premerge-advisor
  labels:
    app: premerge-advisor
spec:
  selector:
    matchLabels:
      app: premerge-advisor
  template:
    metadata:
      labels:
        app: premerge-advisor
    spec:
      volumes:
        - name: advisor-db-volume
          persistentVolumeClaim:
            claimName: advisor-db-pvc
      containers:
        - name: advisor
          image: ghcr.io/llvm/premerge-advisor:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: "/db"
              name: advisor-db-volume
          env:
            - name: ADVISOR_DB_PATH
              value: "/db/advisor_db.sqlite"
          ports:
          -  containerPort: 5000
