name: Build Premerge Advisor Container

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-premerge-advisor-container.yml
      - 'premerge/advisor/**'
  pull_request:
    paths:
      - .github/workflows/build-premerge-advisor-container.yml
      - 'premerge/advisor/**'

jobs:
  build-premerge-advisor-container:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout LLVM Zorg
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          sparse-checkout: premerge/advisor
      - name: Build Container
        uses: llvm/llvm-project/.github/actions/build-container@e6206d567b1d2d324d26465547348fd8a59e2f4e
        with:
          container-name: premerge-advisor
          context: premerge/advisor

  push-premerge-advisor-container:
    if: github.event_name == 'push'
    needs:
      - build-premerge-advisor-container
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: llvm/llvm-project/.github/actions/push-container@e6206d567b1d2d324d26465547348fd8a59e2f4e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}