name: Build Operations Metrics Container

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-operations-metrics-container.yml
      - 'premerge/ops-container/**'
  pull_request:
    paths:
      - .github/workflows/build-operations-metrics-container.yml
      - 'premerge/ops-container/**'

jobs:
  build-operations-metrics-container:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout LLVM Zorg
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: premerge/ops-container
      - name: Build Container
        uses: llvm/llvm-project/.github/actions/build-container@9ee130fa0c8bb163b69923f203f3b2399fea747d
        with:
            container-name: operations-metrics
            context: premerge/ops-container

  push-operations-metrics-container:
    if: github.event_name == 'push'
    needs:
      - build-operations-metrics-container
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: llvm/llvm-project/.github/actions/push-container@9ee130fa0c8bb163b69923f203f3b2399fea747d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
