name: Build Premerge Advisor Container

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-premerge-advisor-container.yml
      - 'premerge/advisor/**'
  pull_request:
    paths:
      - .github/workflows/build-premerge-advisor-container.yml
      - 'premerge/advisor/**'

jobs:
  build-premerge-advisor-container:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout LLVM Zorg
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: premerge/advisor
      - name: Build Container
        uses: llvm/llvm-project/.github/actions/build-container@883aa1207e0319362f9b9907158520d28f45fb72
        with:
          container-name: premerge-advisor
          context: premerge/advisor

  push-premerge-advisor-container:
    if: github.event_name == 'push'
    needs:
      - build-premerge-advisor-container
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: llvm/llvm-project/.github/actions/push-container@883aa1207e0319362f9b9907158520d28f45fb72
        with:
          token: ${{ secrets.GITHUB_TOKEN }}