name: Build Operations Metrics Container

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-operations-metrics-container.yml
      - 'premerge/ops-container/**'
  pull_request:
    paths:
      - .github/workflows/build-operations-metrics-container.yml
      - 'premerge/ops-container/**'

jobs:
  build-operations-metrics-container:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    outputs:
      container-name: ${{ steps.vars.outputs.container-name }}
      container-name-tag: ${{ steps.vars.outputs.container-name-tag }}
      container-filename: ${{ steps.vars.outputs.container-filename }}
    steps:
      - name: Checkout LLVM Zorg
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: premerge/ops-container
      - name: Write Variables
        id: vars
        run: |
          tag=`date +%s`
          container_name="ghcr.io/$GITHUB_REPOSITORY_OWNER/operations-metrics"
          echo "container-name=$container_name" >> $GITHUB_OUTPUT
          echo "container-name-tag=$container_name:$tag" >> $GITHUB_OUTPUT
          echo "container-filename=$(echo $container_name:$tag  | sed -e 's/\//-/g' -e 's/:/-/g').tar" >> $GITHUB_OUTPUT
      - name: Build Container
        working-directory: premerge/ops-container
        run: |
          podman build -t ${{ steps.vars.outputs.container-name-tag }} .
      # Save the container so we have it in case the push fails.  This also
      # allows us to separate the push step into a different job so we can
      # maintain minimal permissions while building the container.
      - name: Save Container Image
        run: |
          podman save  ${{ steps.vars.outputs.container-name-tag }} >  ${{ steps.vars.outputs.container-filename }}
      - name: Upload Container Image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: container
          path: ${{ steps.vars.outputs.container-filename }}
          retention-days: 14

  push-operations-metrics-container:
    if: github.event_name == 'push'
    needs:
      - build-operations-metrics-container
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download Container Image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: container
      - name: Push Container
        run: |
          podman load -i ${{ needs.build-operations-metrics-container.outputs.container-filename }}
          podman tag ${{ needs.build-operations-metrics-container.outputs.container-name-tag }} ${{ needs.build-operations-metrics-container.outputs.container-name }}:latest
          podman login -u ${{ github.actor }} -p $GITHUB_TOKEN ghcr.io
          podman push ${{ needs.build-operations-metrics-container.outputs.container-name-tag }}
          podman push ${{ needs.build-operations-metrics-container.outputs.container-name }}:latest
