name: llvm-zorg testing

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check_zorg:
    name: llvm-zorg litmus tests
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-18-tools
        sudo ln -s /usr/lib/llvm-18/build/utils/lit/lit.py /usr/bin/lit
        sudo ln -s /usr/bin/FileCheck-18 /usr/bin/FileCheck
        python3 -m venv venv
        source venv/bin/activate
        pip install buildbot{,-worker}==3.11.7 urllib3
        echo "PATH=$PATH" >> "$GITHUB_ENV"
    - name: Run lit tests
      run: lit -v --xfail jenkins/test_build.py test
    - name: Run buildbot checkconfig
      run: |
        cd buildbot/osuosl/master
        BUILDBOT_TEST=1 buildbot checkconfig
